### ISSUE TITLE
Thank you for Beatporter

### ISSUE THREAD

**Issue by analogueworld** [rootshellz/Beatporter#5]
Thank you for this great tool. I have no programming skills but I followed your detailed guide and got everything up and running successfully! Thank you for this great tool!

**Comment by rootshellz** [comment]
Hi, glad to hear you were able to get this working.  I had neglected this project for too long, I never realized until now that anyone else was using this tool.  I just made some changes to fix some annoyances.  If you download the latest code in the master branch, you will get some major speed and efficiency improvements and updated genres.
